# Generated by Django 6.0.6 on 2026-06-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chord'),
    ]

    operations = [
        migrations.AddField(
            model_name='chord',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
