# Generated by Django 6.0.6 on 2026-06-20 13:42

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chord_is_public'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='chord',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
