# Generated by Django 6.0.6 on 2026-06-21 06:39

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chord_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='chord',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chord',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
